### ISSUE TITLE
Most leaves not despawning correctly

### ISSUE THREAD

**Issue by Konfuz** [runsy/cool_trees#11]
Clementine-Trees and most others don't remove the leaves after being chopped down. Apparently you (deliberately) set param2 = 1 for the leave nodes in your schematics. Perhaps you misread the documentation, because otherwise your code is fine. 

> 
> If `param2` of any registered node is ~= 0, the node will always be
> preserved. Thus, if the player places a node of that kind, you will
> want to set `param2 = 1` or so.

You want to keep the grown (or generated) leaves at param2 = 0. 
That way only leaves placed by the user will get param2 = 1 set by the subsequent call to after_place. 

Thanks for the nice trees!

**Comment by runsy** [comment]
You mean that the leaves have to set param1 to 0 by default?

**Comment by Konfuz** [comment]
Yes, though I believe if you don't set it explicitly it will be zero by default. The game (rather the default mod) uses param2 to decide between "natural" leaves with param2 = 0 and manually placed leaves with param2 = 1 because you don't want a user generated hedge to de-spawn for example.

**Comment by superfloh247** [comment]
Please apply this change. I'm working on lumberjack integration and felling the cool tree trunks works well, but the leaves just stay hanging in the air.

**Comment by runsy** [comment]
Done.
