### ISSUE TITLE
Field "use_texture_alpha": Boolean values are deprecated; use the new choices

### ISSUE THREAD

**Issue by z0rti** [runsy/cool_trees#15]
On current 5.4.1 i get this:
WARNING[Main]: Field "use_texture_alpha": Boolean values are deprecated; use the new choices

According to https://dev.minetest.net/Changelog 
```
Deprecated node field value: use_texture_alpha = true/false
Fix: Use "clip", "blend" or "opaque" (see documentation)
```

**Comment by runsy** [comment]
Solved.
