### ISSUE TITLE
Leaf decay

### ISSUE THREAD

**Issue by VanessaE** [runsy/cool_trees#18]
Please go through all of the trees and add leaf decay where possible.  In general this is simply a group you set on the leaves nodes, then the engine and its helper code handles the rest.  For example, this is what's used on mtg default leaves:

`groups = {snappy = 3, leafdecay = 3, flammable = 2, leaves = 1}`

I believe the value for `leafdecay` here is the radius from the trunk.

**Comment by runsy** [comment]
Leafdeacay group is deprecated, read:
https://forum.minetest.net/viewtopic.php?p=255213#p255213

**Comment by VanessaE** [comment]
Oh, I didn't realize that it had changed.  However, it seems that many trees do not decay.

**Comment by runsy** [comment]
> 
> 
> Oh, I didn't realize that it had changed. However, it seems that many trees do not decay.

Can you give me an example?

**Comment by VanessaE** [comment]
Well, birch, oak, and palm seem fine at least.  Bamboo too.

On the other hand, maple, larch, cherry, and bald cypress trees don't appear to decay.

There may be others.

**Comment by runsy** [comment]
> 
> 
> Well, birch, oak, and palm seem fine at least. Bamboo too.
> 
> On the other hand, maple, larch, cherry, and bald cypress trees don't appear to decay.
> 
> There may be others.

I've made a fix 15 days ago:
"changed param2 to 1 for leaves and fruits"

but for new trees unfortunately. I you could check with a brand new tree...

**Comment by VanessaE** [comment]
For the above comment, I was using a new map, though my copy of cool_trees is a bit old (which is strange, as I am certain I brought things up-to-date recently).

**Comment by VanessaE** [comment]
OK, maple, larch, and cypress decay now, but cherry trees don't.

**Comment by VanessaE** [comment]
(ignore that close action, misclick.  see previous comment about cherry trees)

**Comment by runsy** [comment]
> 
> 
> OK, maple, larch, and cypress decay now, but cherry trees don't.

You're right, the blossom leaves were not registered for decay.

I've commited a fix: "Register leafdecay for Cheery Blossom Leaves"

So I think now it is solved.

**Comment by VanessaE** [comment]
Yeah, everything seems good now.
