### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by axcore** [runsy/cool_trees#30]
Spotted a few typos/bugs, a few serious, most not serious:

1. /cacaotree/init.lua line 117, the name is cacao:cacaotree but this mod does not exist, should be cacaotree:cacaotree
2. Bonemeal works  on palm saplings on dirt, but doesn't work on sand (for no obvious reason)
3. /plumtree/init.lua line 46 refers to "plumtree:blossom_leaves" but that does not exist. I think it's a copy and paste error from another tree

Minor issues:

1. /palm/init.lua line 194, there is no node=1 group (all the other doors have node=1). I don't know if this is deliberate or not
2. /jacaranda/init.lua, the fences and gates are described as "Jaceranda", should be "Jacaranda" (lines 170, 177, 181)
3. The sequoia tree has no flowerpot, for some reason (all other trees have flowerpots)
5. Lemon tree code mentions the cork mod, but that mod isn't in mod.conf
6. /cacaotree/init.lua line 244, the "Cacaotree Flower Creeper" should be a "Cacao Tree Flower Creeper" (to be consistent with other descriptions in that file)
7. /cherrytree/init.lua line 161, the "Cherrytree Blossom leaves" should be "Cherry Tree Blossom Leaves" (to be consistent with other descriptions in that file)
8. /cacaotree/init.lua line 86, the cake is called "Choco Cake" but this term does not exist in English, it should probably be "Chcocolate Cake"

**Comment by axcore** [comment]
The position of the willow schematic is slightly wrong. Line 21 should be

`	minetest.place_schematic({x = pos.x-4, y = pos.y, z = pos.z-5}, modpath.."/schematics/willow.mts", "0", nil, false)`

**Comment by axcore** [comment]
The node `cherrytree:leaves` is defined but not used by anything, not even the schematic. Perhaps it can be in the `not_in_creative_inventory` group so players don't waste valuable time, trying to work out how to grow it.

**Comment by axcore** [comment]
Fruits stay hanging in the air, when the rest of the tree is destroyed. This looks very weird. Probably the fruits (including burs etc) should be added to leafdecay.

**Comment by runsy** [comment]
fixed in the last commit.
