### ISSUE TITLE
`cherrytree:leaves` node definition missing after latest commits

### ISSUE THREAD

**Issue by BuckarooBanzay** [runsy/cool_trees#34]
After https://github.com/runsy/cool_trees/compare/af8e445c475efb050c1291da459336812b84591e...5830a0f67429b25f99eab504a3a8d3f009f52b39#diff-b30ad726cabdf9b7d3eacbfefb2cc98b62d018f9434b6bd4cb4e305a6d3b2fdfL190-L207

CC @waxtatect (sorry 😆)

**Comment by waxtatect** [comment]
hmm where is the issue with those leaves?
as mentioned here it's unused https://github.com/runsy/cool_trees/issues/30#issuecomment-1159682483

**Comment by runsy** [comment]
In the past that leave sturn into blossom ones and viceversa.

I re-added them for compatibility.

**Comment by OgelGames** [comment]
> what to do about it?

If they are completely unused, then you could remove them, but you must add an alias for them, like this:

```lua
minetest.register_alias("cherrytree:leaves", "cherrytree:blossom_leaves")
```

BTW, @runsy you forgot to re-add the texture ;)

**Comment by runsy** [comment]
Fixed: Texture readded.

It is marked as deprecated. So Cool Trees users should remove from your games/servers. In the future will be removed.
