### ISSUE TITLE
Trunk nodes shouldn't define `on_rightclick`

### ISSUE THREAD

**Issue by OgelGames** [runsy/cool_trees#7]
Originally reported in pandorabox-io/pandorabox.io#397 for the cherry tree.

A number of trees in this modpack cannot be built on due to their trunk nodes defining `on_rightclick`. 

I decided not to fix it myself because of the lemon tree using the callback to support the `cork` mod, which I suggest changing in some way so that all the code is contained in the `cork` mod, similar to how the tree tap from `technic` works: https://github.com/minetest-mods/technic/blob/master/technic/tools/tree_tap.lua#L8

**Comment by runsy** [comment]
What specific trunks?

Cherry was solved.

**Comment by OgelGames** [comment]
> What specific trunks?

All the ones with `on_rightclick` defined - cherry, ebony, jacaranda, larch, lemon, and mahogany. None of them can be built on.

I can fix it and open a PR if you want, I just thought it would be better for you to fix...

**Comment by runsy** [comment]
I've made the fixes.
